# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}
    - run: yarn install
    # Runs a single command using the runners shell
    #- name: Run a one-line script
     # run: echo Hello, world!
    - name: Typescript (tsc) Build/Push
      uses: FuLagann/tsc-build-push@v1
      with:
        # The name of a contributor of the repository, used for pushing to git.
        user-name: a7urag
        # The email of a contributor of the repository, used for pushing to git.
        user-email: a7urag@gmail.com
        # The commit message that will appear when a build has completed.
        message: # default is Automatically built unbuilt typescript
        # The list of directories to build the typescripts from, if omitted then it will use the base project directory. The list is seperated by comma that's not found within quotations.
        directories: # optional
    - run: yarn test
